services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - 15000:3000
    tty: true
    volumes:
      - ./:/project/next-playground:cached
